//======================================================
// Source code generated by jvider v1.8.1 UNREGISTERED version.
// http://www.jvider.com/
//======================================================
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class lols extends JPanel {
   
    private JButton A2;
    private JButton A4;
    private JButton A5;
    private JButton A7;
    private JButton A6;
    private JButton A3;
    private JButton A1;
    private JButton A8;
    private JButton A9;
    private JButton A10;
    private JButton B2;
    private JButton C1;
    private JButton D1;
    private JButton E1;
    private JButton F1;
    private JButton H1;
    private JButton I1;
    private JButton G1;
    private JLabel Label_1;
    private JLabel Label_2;
    private JLabel Label_3;
    private JLabel Label_A;
    private JLabel Label_B;
    private JLabel Label_C;
    private JLabel Label_D;
    private JLabel Label_E;
    private JLabel Label_F;
    private JLabel Label_G;
    private JLabel Label_H;
    private JLabel Label_I;
    private JComboBox Seletor;
    private JButton NovoJogo;
    private JButton Reiniciar;
    private JTextField Pontuacao;

    public lols() {
        //construct preComponents
        String[] SeletorItems = {"Item 1", "Item 2", "Item 3", "Item 4"};

        //construct components
        A1 = new JButton ("A1");
        A2 = new JButton ("A2");
        A3 = new JButton ("A3");
        A4 = new JButton ("A4");
        A5 = new JButton ("A5");
        A6 = new JButton ("A6");
        A7 = new JButton ("A7");
        A8 = new JButton ("A8");
        A9 = new JButton ("A9");
        A10 = new JButton ("A10");
        B2 = new JButton ("B1");
        C1 = new JButton ("C1");
        D1 = new JButton ("D1");
        E1 = new JButton ("E1");
        F1 = new JButton ("F1");
        H1 = new JButton ("H1");
        I1 = new JButton ("I1");
        G1 = new JButton ("G1");
        Label_1 = new JLabel ("1");
        Label_2 = new JLabel ("2");
        Label_3 = new JLabel ("3");
        Label_A = new JLabel ("A");
        Label_B = new JLabel ("B");
        Label_C = new JLabel ("C");
        Label_D = new JLabel ("D");
        Label_E = new JLabel ("E");
        Label_F = new JLabel ("F");
        Label_G = new JLabel ("G");
        Label_H = new JLabel ("H");
        Label_I = new JLabel ("I");
        Seletor = new JComboBox (SeletorItems);
        NovoJogo = new JButton ("Novo Jogo");
        Reiniciar = new JButton ("Reiniciar");
        Pontuacao = new JTextField (5);

        //adjust size and set layout
        setPreferredSize (new Dimension (617, 617));
        setLayout (null);

        //add components
        add (A2);
        add (A4);
        add (A5);
        add (A7);
        add (A6);
        add (A3);
        add (A1);
        add (A8);
        add (A9);
        add (A10);
        add (B2);
        add (C1);
        add (D1);
        add (E1);
        add (F1);
        add (H1);
        add (I1);
        add (G1);
        add (Label_1);
        add (Label_2);
        add (Label_3);
        add (Label_A);
        add (Label_B);
        add (Label_C);
        add (Label_D);
        add (Label_E);
        add (Label_F);
        add (Label_G);
        add (Label_H);
        add (Label_I);
        add (Seletor);
        add (NovoJogo);
        add (Reiniciar);
        add (Pontuacao);

        //set component bounds (only needed by Absolute Positioning)
        A1.setBounds (40, 60, 50, 50);
        A2.setBounds (95, 60, 50, 50);
        A3.setBounds (150, 60, 50, 50);
        A4.setBounds (205, 60, 50, 50);
        A5.setBounds (260, 60, 50, 50);
        A7.setBounds (370, 60, 50, 50);
        A6.setBounds (315, 60, 50, 50);
        A8.setBounds (425, 60, 50, 50);
        A9.setBounds (480, 60, 50, 50);
        A10.setBounds (535, 60, 50, 50);
        B2.setBounds (40, 115, 50, 50);
        C1.setBounds (40, 170, 50, 50);
        D1.setBounds (40, 225, 50, 50);
        E1.setBounds (40, 280, 50, 50);
        F1.setBounds (40, 335, 50, 50);
        G1.setBounds (40, 390, 50, 50);
        H1.setBounds (40, 445, 50, 50);
        I1.setBounds (40, 500, 50, 50);
        Label_1.setBounds (60, 35, 25, 25);
        Label_2.setBounds (115, 35, 25, 25);
        Label_3.setBounds (170, 35, 25, 25);
        Label_A.setBounds (15, 75, 25, 25);
        Label_B.setBounds (15, 130, 25, 25);
        Label_C.setBounds (15, 190, 25, 25);
        Label_D.setBounds (15, 245, 25, 25);
        Label_E.setBounds (15, 300, 25, 25);
        Label_F.setBounds (15, 355, 25, 25);
        Label_G.setBounds (15, 410, 25, 25);
        Label_H.setBounds (15, 465, 25, 25);
        Label_I.setBounds (15, 510, 25, 25);
        Seletor.setBounds (40, 5, 545, 30);
        NovoJogo.setBounds (40, 565, 100, 25);
        Reiniciar.setBounds (485, 565, 100, 25);
        Pontuacao.setBounds (145, 565, 335, 25);
    }
} 
